### PR TITLE
Websockets feedback and compatibility to all versions of Playdeck

### PR DESCRIPTION
**Pull request by semenovnick**
Hello. I'm just renewed the code of module to be compatible to all versions of Playdeck and add new WebSocket connection.

### CODE REVIEW

**Comment by kev-ac** [comment]
Hi @semenovnick, 
Kevin here from JOY event & media / PLAYDECK. 

We'd like to thank you for your extensive contributions to the PLAYDECK Companion module.
Feel free to drop us a message to support@playdeck.tv with a reference to my comment :-).

**Comment by semenovnick** [comment]
> Hi @semenovnick, Kevin here from JOY event & media / PLAYDECK.
> 
> We'd like to thank you for your extensive contributions to the PLAYDECK Companion module. Feel free to drop us a message to [support@playdeck.tv](mailto:support@playdeck.tv) with a reference to my comment :-).

Thank you for appreciating my work. Dropped you a message to [that mail](mailto:support@playdeck.tv)

**Comment by kev-ac** [comment]
We sadly were not able to locale an email from you. Not in our support inbox nor filtered as spam. 
Could you please verify that the email address does not contain a typo? ([support@playdeck.tv](mailto:support@playdeck.tv)).

Otherwise if you're comfortable with sharing your email address here feel free to do that and we will reach out to you!

**Comment by semenovnick** [comment]
> We sadly were not able to locale an email from you. Not in our support inbox nor filtered as spam. Could you please verify that the email address does not contain a typo? ([support@playdeck.tv](mailto:support@playdeck.tv)).
> 
> Otherwise if you're comfortable with sharing your email address here feel free to do that and we will reach out to you!

My mail: semenov_nick@mail.ru

**Pull request merged**
